[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32H7S3L8Hx --protocol swd --connect-under-reset'

[env]
DEFMT_LOG = "debug"
